import { NextRequest, NextResponse } from 'next/server';
import { getSessionDetail, saveSummary } from '@/lib/db';

interface RouteParams {
  params: Promise<{ sessionId: string }>;
}

export async function POST(
  request: NextRequest,
  { params }: RouteParams
) {
  try {
    const { sessionId } = await params;

    // Get session detail with transcript
    const { session, transcript } = await getSessionDetail(sessionId);

    if (transcript.length === 0) {
      return NextResponse.json(
        { error: 'No transcript available to summarize' },
        { status: 400 }
      );
    }

    // TODO: Call LLM API (OpenAI) to generate actual summary
    // For now, generate a stub summary
    const transcriptText = transcript
      .map((turn) => `${turn.role}: ${turn.text}`)
      .join('\n\n');

    const summaryText = `Session Summary (Stub)
    
This is a placeholder summary. In production, this would be generated by an LLM analyzing the transcript.

Session with ${session.agent?.name || 'agent'} on ${new Date(session.started_at).toLocaleDateString()}.

Transcript length: ${transcript.length} turns
Total duration: ${session.ended_at ? 'Completed' : 'Ongoing'}

[LLM summarization will be implemented here to extract:
- Topics discussed
- Emotional themes
- Patterns or cognitive distortions
- Tools or strategies mentioned
- Action items / next steps
- Follow-up prompts]`;

    const summaryJson = {
      topics: ['Placeholder topic'],
      emotional_themes: ['Placeholder theme'],
      patterns: ['Placeholder pattern'],
      tools_mentioned: [],
      action_items: ['Implement LLM summarization'],
      follow_up_prompts: ['How did this session help you?'],
    };

    // Save summary
    await saveSummary(sessionId, summaryText, summaryJson);

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error generating summary:', error);
    return NextResponse.json(
      { error: 'Failed to generate summary' },
      { status: 500 }
    );
  }
}
